In [1]:

import pandas as pd
import numpy as np

# Set a seed for reproducibility
np.random.seed(42)

# Create a dictionary to store the data
data = {
    'r1': np.random.randint(1, 34, size=1000),
    'r2': np.random.randint(1, 10001, size=1000)
}

# Create the DataFrame
df = pd.DataFrame(data)

# Calculate r3 based on the formula r1 + r2 * 20
df['r3'] = df['r1'] + df['r2'] **3 + df['r1'] * df['r2']+20

# Display the DataFrame
print(df)

     r1    r2            r3
0    29  9829  949572514879
1    15  4091   68468186971
2     8  6961  337298937397
3    21  3005   27135288271
4    19  5137  135559203995
..   ..   ...           ...
995  25   770     456552295
996   3   781     476381907
997  30  9909  972947973749
998  12  6304  250523658144
999  19  3984   63235143639

[1000 rows x 3 columns]

In [2]:
from pycaret.regression import *

In [3]:
selected_models = setup( data = df, 
                        target = "r3", session_id=43,
                        transformation=True,
#                        fix_imbalance = True, #8:2
                        normalize=True,
                    
                        )

In [4]:
best_from_selection= compare_models()

Processing:   0%|          | 0/85 [00:00<?, ?it/s]